package test;

class ThrowTest {
    static int test(int i) {
        if (i <= 0) throw new ArithmeticException("EEE");
        return ThrowTest.test(i-1);
    }

    static void main(String args) {
        try {
            ThrowTest.test(10);
        } catch (ArithmeticException e) {
            System.print("Error: " + e.message);
        }
    }
}